name: sleep_kids_app_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.0
  # shelf_io: ^1.1.0
  shelf_cors_headers: ^0.1.5
  postgres: ^2.4.0  # Add this for PostgreSQL interaction (or another appropriate package for your database)
  http: ^1.3.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

